export const PREVIOUS_SLIDE = 'PREVIOUS_SLIDE'
export const NEXT_SLIDE = 'NEXT_SLIDE'
export const SET_TOTAL_SLIDES = 'SET_TOTAL_SLIDES'

export const FETCH_PRESENTATION = 'FETCH_PRESENTATION'
export const FETCH_PRESENTATION_SUCCEEDED = 'FETCH_PRESENTATION_SUCCEEDED'

export const FETCH_PRESENTATIONS = 'FETCH_PRESENTATIONS'
export const FETCH_PRESENTATIONS_SUCCEEDED = 'FETCH_PRESENTATIONS_SUCCEEDED'
