module.exports = {
  TITLE: 'TITLE',
  CODE: 'CODE',
  EMPTY: 'EMPTY',
  TEXT: 'TEXT',
  SLIDE: 'SLIDE',
  SECONDARY: 'SECONDARY',
  NORMAL: 'NORMAL',
  HIGHLIGHTED: 'HIGHLIGHTED',
  LIST_ITEM: 'LIST_ITEM',
  LIST: 'LIST'
};
