module.exports = {
  TITLE: 'TITLE',
  TABLE_ROW: 'TABLE_ROW',
  TABLE: 'TABLE',
  CODE: 'CODE',
  EMPTY: 'EMPTY',
  TEXT: 'TEXT',
  SLIDE: 'SLIDE',
  SECONDARY: 'SECONDARY',
  NORMAL: 'NORMAL',
  HIGHLIGHTED: 'HIGHLIGHTED',
  LIST_ITEM: 'LIST_ITEM',
  LIST: 'LIST',
  LINK: 'LINK'
}
